apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # Path on the host where the data will be stored
