apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80  # The port exposed outside the cluster
      targetPort: 5000  # The port your Flask app listens on inside the cluster
