# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: flask-app
#   ports:
#     - protocol: TCP
#       port: 80  # The port exposed outside the cluster
#       targetPort: 5000  # The port your Flask app listens on inside the cluster

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80  # Port accessible inside the cluster
      targetPort: 5000  # Port where the Flask app is listening
      nodePort: 30001  # External port
  type: NodePort
