apiVersion: v1
kind: Pod
metadata:
  name: pv-inspector
spec:
  containers:
  - name: pv-inspector
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - mountPath: "/mnt"
      name: shared-pv
  volumes:
  - name: shared-pv
    persistentVolumeClaim:
      claimName: shared-pvc