apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-deployment
  namespace: sleeper-build-namespace  # Ensure other pods use this
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: model-training
        image: markjesh/model_training_image:latest
        volumeMounts:
        - mountPath: /app
          name: data-processing-pv
        env:
        - name: TRAIN_DIR
          value: "/app/preprocessed/data/processed_data"  # Updated to reflect where the preprocessed data is located
        - name: VALIDATION_DIR
          value: "/app/preprocessed/data/processed_data"  # Updated to reflect where the preprocessed data is located
      volumes:
      - name: data-processing-pv
        persistentVolumeClaim:
          claimName: data-processing-pvc