apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-deployment  
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: model-training
        image: markjesh/model-training-image:latest
        volumeMounts:
        - mountPath: "/mnt"
          name: shared-pv
      volumes:
      - name: shared-pv
        persistentVolumeClaim:
          claimName: shared-pvc
