apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-deployment
  namespace: my-application-namespace  # Ensure other pods use this
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: model-training
        image: model_training_image:latest
        volumeMounts:
        - mountPath: "/app/models"
          name: model-storage
        - mountPath: "/app/preprocessed"  # Mount for the preprocessing PVC
          name: preprocessing-storage     # Name referencing the preprocessing PVC
        env:
        - name: TRAIN_DIR
          value: "/app/preprocessed/train"  # Updated to reflect where the preprocessed data is located
        - name: VALIDATION_DIR
          value: "/app/preprocessed/validation"  # Updated to reflect where the preprocessed data is located
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
      - name: preprocessing-storage  # New volume for the preprocessing PVC
        persistentVolumeClaim:
          claimName: preprocessing-pvc  # Make sure this matches the PVC used by preprocessing