apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-inference-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: model-inference
  template:
    metadata:
      labels:
        app: model-inference
    spec:
      containers:
      - name: model-inference
        image: markjesh/inference:v2
        volumeMounts:
        - mountPath: "/mnt"
          name: shared-pv
        ports:
        - containerPort: 5000
      volumes:
      - name: shared-pv  
        persistentVolumeClaim:
          claimName: shared-pvc 
