apiVersion: v1
kind: Pod
metadata:
  name: dataInference-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: dataInference
    image: nigelpoulton/k8sbook:1.0
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: 256Mi
        cpu: 0.5