# Namespace Definition
apiVersion: v1
kind: Namespace
metadata:
  name: my-application-namespace

---

# Persistent Volume (PV) Definition
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
  namespace: my-application-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/models"

---

# Persistent Volume Claim (PVC) Definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: my-application-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi