apiVersion: v1
kind: Service
metadata:
  name: inference-svc
  namespace: my-application-namespace
  labels:
    app: inference-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80 
    targetPort: 5000
    protocol: TCP
  selector:
    app: model-inference