apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-processing-pv
  namespace: sleeper-build-namespace
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/app"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-processing-pvc
  namespace: sleeper-build-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Namespace
metadata:
  name: sleeper-build-namespace