apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: data-processing
  template:
    metadata:
      labels:
        app: data-processing
      name: data-processing-pod
    spec:
      containers:
      - name: data-processing-container
        image: markjesh/data-processing-image:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-pv
          mountPath: "/mnt"
      volumes:
      - name: shared-pv
        persistentVolumeClaim:
          claimName: shared-pvc
