# Docker file for data processing

# Use python 3.8 as a base image
FROM python:3.9

# Set working directory for subsequent commands
WORKDIR /app

# Copy only the necessary files and directories
COPY dockerfile /app/
COPY data_processing.py /app/
COPY parameters.py /app/
COPY requirements.txt /app/
COPY raw_data /app/raw_data

# Install system dependencies required by OpenCV
RUN apt-get update && apt-get install -y libgl1

# Install the dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Run the data processing script
CMD ["python", "data_processing.py"]