# Docker file for data processing

# Use python 3.8 as a base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the content of the local src directory to the working directory
COPY . .
COPY . /app

# Install system dependencies required by OpenCV
RUN apt-get update && apt-get install -y libgl1

# Install the dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt


# Run the data processing script
CMD ["python", "data_processing.py"]